module.exports = {
    app_title     : 'Demo layihə',
    welcome_title : 'Layihə Vue.js-lə hazırlanıb',
    made_with     : 'İstifadə olunan texnologiyalar: Backend/Node.js, NoSQL/Firebase, PaaS/Heroku, CI/Codeship, Frontend/Vuetify',
    sign_in_title : 'Sistemə giriş',
    sign_up_title : 'Sistemdə qeydiyyat',
    sign_in       : 'Daxil Ol',
    btn_sign_in   : 'Daxil ol',
    sign_up       : 'Qeyd Ol',
    btn_sign_up   : 'Qeydiyyat',
    btn_clear     : 'Təmizlə',
    home          : 'Baş səhifə',
    password_label: 'Baş səhifə',
    email_label   : 'Baş səhifə',
    btn_loading   : 'Qeydiyyat...',
    sign_out      : 'Çıxış',
};